version: "3"

services:
  car-manager:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    image: with-docker-multi-env-production
    networks:
        - "default"
    container_name: car-manager    
    
    
networks:
  default:
    name: ngixproxymanager_default
    external: true

