version: "3"

services:
  car-manager:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    image: car-manager-app
    networks:
        - "default"
    container_name: car-manager
    ports:
      - "3003:3000"    
    
    
networks:
  default:
    name: ngixproxymanager_default
    external: true

